name: my-golang-ci-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - run: go get github.com/stretchr/testify@v1.8.4
      - run: go mod tidy
      - run: go test
      - run: go run main.go
